Updating the tekton files and adding json template

diff --git a/.tekton/task-pr-ubuntu.yaml b/.tekton/task-pr-ubuntu.yaml
--- a/.tekton/task-pr-ubuntu.yaml
+++ b/.tekton/task-pr-ubuntu.yaml
@@ -27,9 +27,9 @@ spec:
     - name: ssh_keys
       default: ""
       description: List of names of the SSH keys that is configured in your IBM Cloud account, used to establish a connection to the IBM Cloud HPC bastion and login node. Ensure that the SSH key is present in the same resource group and region where the cluster is being provisioned. If you do not have an SSH key in your IBM Cloud account, create one by according to [SSH Keys](https://cloud.ibm.com/docs/vpc?topic=vpc-ssh-keys).
-    - name: zones
+    - name: zone
       default: ""
-      description: IBM Cloud zone names within the selected region where the IBM Cloud HPC cluster should be deployed. Two zone names are required as input value and supported zones for eu-de are eu-de-2, eu-de-3 and for us-east us-east-1, us-east-3. The management nodes and file storage shares will be deployed to the first zone in the list. Compute nodes will be deployed across both first and second zones, where the first zone in the list will be considered as the most preferred zone for compute nodes deployment. [Learn more](https://cloud.ibm.com/docs/vpc?topic=vpc-creating-a-vpc-in-a-different-region#get-zones-using-the-cli).
+      description: The IBM Cloud zone name within the selected region where the IBM Cloud HPC cluster should be deployed and requires a single zone input value. Supported zones are eu-de-2 and eu-de-3 for eu-de, us-east-1 and us-east-3 for us-east, and us-south-1 for us-south. The management nodes, file storage shares, and compute nodes will be deployed in the same zone.[Learn more](https://cloud.ibm.com/docs/vpc?topic=vpc-creating-a-vpc-in-a-different-region#get-zones-using-the-cli).
     - name: cluster_prefix
       description: Prefix that is used to name the IBM Cloud HPC cluster and IBM Cloud resources that are provisioned to build the IBM Cloud HPC cluster instance. You cannot create more than one instance of the IBM Cloud HPC cluster with the same name. Ensure that the name is unique.
       default: cicd-wes
@@ -54,6 +54,9 @@ spec:
     - name: reservation_id
       description: Ensure that you have received the reservation ID from IBM technical sales. Reservation ID is a unique identifier to distinguish different IBM Cloud HPC service agreements. It must start with a letter and can only contain letters, numbers, hyphens (-), or underscores (_).
       default: ""
+    - name: pr-revision
+      description: the commit/revision in the source branch of the PullRequest that is to be built
+      default: ""
   workspaces:
     - name: workspace
       mountPath: /artifacts
@@ -67,6 +70,8 @@ spec:
             optional: true
       - name: PIPELINE_DEBUG
         value: $(params.pipeline-debug)
+      - name: PR_REVISION
+        value: $(params.pr-revision)
   steps:
     - name: test-run-basic-ubuntu-pr
       onError: continue
@@ -74,8 +79,8 @@ spec:
       env:
         - name: ssh_keys
           value: $(params.ssh_keys)
-        - name: zones
-          value: $(params.zones)
+        - name: zone
+          value: $(params.zone)
         - name: resource_group
           value: $(params.resource_group)
         - name: compute_image_name_ubuntu
@@ -100,8 +105,15 @@ spec:
             set -x
           fi
 
-          unzip -n terraform_1.5.7_linux_amd64.zip
-          mv terraform /usr/local/bin/terraform
+          PR_REVISION=$(echo $PR_REVISION)
+          CICD_SSH_KEY=cicd
+          CICD_SSH_KEY=$(echo $CICD_SSH_KEY-$PR_REVISION)
+
+          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
+          echo 'export PATH=$PATH:$HOME/.tfenv/bin' >> ~/.bashrc
+          ln -s ~/.tfenv/bin/* /usr/local/bin
+          tfenv install 1.5.7
+          tfenv use 1.5.7
           terraform --version
 
           cd $(pwd)/ &&
@@ -112,26 +124,18 @@ spec:
 
           export TF_VAR_ibmcloud_api_key=$API_KEY
           export SSH_FILE_PATH="/artifacts/.ssh/id_rsa"
-          CICD_SSH_KEY="cicd-toolchain"
 
           # Check artifacts/tests folder exists or not
           DIRECTORY="/artifacts/tests"
           if [ -d "$DIRECTORY" ]; then
             cd $DIRECTORY
-              LOG_FILE=pipeline-TestRunBasic-ubuntu-$(date +%d%m%Y).cicd
+              LOG_FILE=pipeline-testrunbasic-ubuntu-$(date +%d%m%Y).cicd
               echo "**************Validating on TestRunBasic**************"
-              SSH_KEY=$CICD_SSH_KEY COMPUTE_IMAGE_NAME=$compute_image_name_ubuntu LOGIN_NODE_IMAGE_NAME=$login_image_name ZONE=$zones RESERVATION_ID=$reservation_id CLUSTER_ID=$cluster_id RESOURCE_GROUP=$resource_group go test -v -timeout 9000m -run TestRunBasic | tee -a $LOG_FILE
+              SSH_KEY=$CICD_SSH_KEY COMPUTE_IMAGE_NAME=$compute_image_name_ubuntu LOGIN_NODE_IMAGE_NAME=$login_image_name ZONE=$zone RESERVATION_ID=$reservation_id CLUSTER_ID=$cluster_id RESOURCE_GROUP=$resource_group go test -v -timeout 9000m -run "TestRunDefault" | tee -a $LOG_FILE
           else
             pwd
             ls -a
             echo "$DIRECTORY does not exists"
-            exit 1
-          fi
-
-          # Check any error message on the plan/apply log
-          error_check=$(eval "grep -E -w 'FAIL|Error|ERROR' $DIRECTORY/$LOG_FILE")
-          if [[ "$error_check" ]]; then
-            echo "Found Error/FAIL/ERROR in plan/apply log. Please check log."
             exit 1
           fi
 
@@ -148,5 +152,12 @@ spec:
           count=`ls -1 $DIRECTORY/*.cicd 2>/dev/null | wc -l`
           if [ $count == 0 ]; then
             echo "Test Suite have not initated, check with packages or binaries installation"
+            exit 1
+          fi
+
+          # Check any error message on the plan/apply log
+          error_check=$(eval "grep -E -w 'FAIL|Error|ERROR' $DIRECTORY/$LOG_FILE")
+          if [[ "$error_check" ]]; then
+            echo "Found Error/FAIL/ERROR in plan/apply log. Please check log."
             exit 1
           fi
